image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-notification-service
  tag: replace-with-ci-tag
service:
  port: 7902
env:
  ENV: staging
  SERVICE_PORT: '7902'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: notification-service-secrets
  remotePath: secret/data/lma/notification-service/staging
  keys:
  - RESEND_API_KEY
  - TWILIO_ACCOUNT_SID
  - TWILIO_AUTH_TOKEN
  - SLACK_WEBHOOK_URL
