apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: positioning-engine-service-deny-all
spec:
  podSelector:
    matchLabels:
      app: positioning-engine-service
  policyTypes: ["Ingress","Egress"]
  ingress: [{}]
  egress: [{}]
