image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-agent-ingest-service
  tag: replace-with-ci-tag
service:
  port: 7053
env:
  ENV: staging
  SERVICE_PORT: '7053'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
  AGENT_PUBLIC_KEY_JWKS: ''
  REPORT_MAX_MB: ''
  RESULTS_BUCKET: ''
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: agent-ingest-service-secrets
  remotePath: secret/data/lma/agent-ingest-service/staging
  keys: []
