apiVersion: v1
kind: Service
metadata:
  name: scaffold-secure-service
spec:
  type: ClusterIP
  selector: { app: scaffold-secure-service }
  ports:
    - name: http
      port: 7103
      targetPort: 7103
