apiVersion: v1
kind: Service
metadata:
  name: agent-ingest-service
spec:
  type: ClusterIP
  selector: { app: agent-ingest-service }
  ports:
    - name: http
      port: 7053
      targetPort: 7053
