image:
  repository: ghcr.io/ORG/REPO-db-guardian-service
  tag: latest
service:
  port: 7105
grpc:
  enabled: true
  port: 50065
env: {}
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
