image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-fix-engine-service
  tag: dev
service:
  port: 7151
env:
  ENV: dev
  SERVICE_PORT: '7151'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-dev.svc.cluster.local:4317
  PATCH_MAX_FILES: ''
  PATCH_MAX_LOC: ''
  PATCH_TTL_DAYS: ''
  DIFF_ENGINE: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
hpa:
  enabled: false
externalSecrets:
  enabled: true
  storeRefName: vault-dev
  targetName: fix-engine-service-secrets
  remotePath: secret/data/lma/fix-engine-service/dev
  keys: []
