image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-projects-service
  tag: replace-with-ci-tag
service:
  port: 7002
env:
  ENV: prod
  SERVICE_PORT: '7002'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  JWT_PUBLIC_KEY: ''
  S3_BUCKET_PROJECTS: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: projects-service-secrets
  remotePath: secret/data/lma/projects-service/prod
  keys:
  - DATABASE_URL
