apiVersion: v1
kind: Service
metadata:
  name: launch-engine-service
spec:
  type: ClusterIP
  selector: { app: launch-engine-service }
  ports:
    - name: http
      port: 7502
      targetPort: 7502
