image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-billing-service
  tag: replace-with-ci-tag
service:
  port: 7901
env:
  ENV: staging
  SERVICE_PORT: '7901'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
  BILLING_TAX_REGION: ''
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: billing-service-secrets
  remotePath: secret/data/lma/billing-service/staging
  keys:
  - STRIPE_WEBHOOK_SECRET
