package analyzer

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// RoleAnalyzer analyzes database roles for privilege escalation risks.
type RoleAnalyzer struct {
	inspector DBInspector
}

// NewRoleAnalyzer creates a new role analyzer.
func NewRoleAnalyzer(inspector DBInspector) *RoleAnalyzer {
	return &RoleAnalyzer{inspector: inspector}
}

// Analyze performs role privilege analysis.
func (a *RoleAnalyzer) Analyze(ctx context.Context, opts AnalyzeOptions) (*RoleAnalysisResult, error) {
	// Fetch roles from database
	roles, err := a.inspector.GetRoles(ctx)
	if err != nil {
		return nil, fmt.Errorf("fetch roles: %w", err)
	}

	result := &RoleAnalysisResult{
		Findings:      []RoleFinding{},
		AnalyzedAt:    time.Now(),
		RolesAnalyzed: len(roles),
	}

	// Analyze each role
	for _, role := range roles {
		findings := a.analyzeRole(role)
		result.Findings = append(result.Findings, findings...)
	}

	// Generate policy YAML from roles
	result.PolicyYAML = a.generatePolicyYAML(roles)

	return result, nil
}

// analyzeRole checks a single role for security issues.
func (a *RoleAnalyzer) analyzeRole(role RoleInfo) []RoleFinding {
	var findings []RoleFinding

	// Check for superuser privilege (CRITICAL)
	if role.IsSuperuser {
		findings = append(findings, RoleFinding{
			Finding: Finding{
				Severity:    SeverityCritical,
				Category:    "privilege_escalation",
				Title:       "Superuser privilege detected",
				Description: fmt.Sprintf("Role '%s' has SUPERUSER privilege, granting unrestricted database access", role.Name),
				Remediation: "Create a restricted role with only required privileges. Use least-privilege principle.",
			},
			RoleName: role.Name,
		})
	}

	// Check for dangerous privileges (WARN)
	for _, perm := range role.Permissions {
		switch perm.Privilege {
		case "CREATEROLE":
			findings = append(findings, RoleFinding{
				Finding: Finding{
					Severity:    SeverityWarn,
					Category:    "high_privilege",
					Title:       "CREATEROLE privilege detected",
					Description: fmt.Sprintf("Role '%s' can create new roles, enabling potential privilege escalation", role.Name),
					Remediation: "Remove CREATEROLE if not required. Use dedicated admin role if needed.",
				},
				RoleName: role.Name,
			})

		case "CREATEDB":
			findings = append(findings, RoleFinding{
				Finding: Finding{
					Severity:    SeverityInfo,
					Category:    "high_privilege",
					Title:       "CREATEDB privilege detected",
					Description: fmt.Sprintf("Role '%s' can create databases", role.Name),
					Remediation: "Consider whether database creation is necessary for application role.",
				},
				RoleName: role.Name,
			})
		}
	}

	return findings
}

// generatePolicyYAML creates a YAML policy document from roles.
func (a *RoleAnalyzer) generatePolicyYAML(roles []RoleInfo) string {
	var sb strings.Builder

	sb.WriteString("# Database Role Policy\n")
	sb.WriteString("# Generated by db-guardian-service\n")
	sb.WriteString("version: v1\n")
	sb.WriteString("roles:\n")

	for _, role := range roles {
		sb.WriteString(fmt.Sprintf("  - name: %s\n", role.Name))
		sb.WriteString(fmt.Sprintf("    can_login: %t\n", role.CanLogin))
		sb.WriteString(fmt.Sprintf("    is_superuser: %t\n", role.IsSuperuser))

		if len(role.Permissions) > 0 {
			sb.WriteString("    permissions:\n")
			for _, perm := range role.Permissions {
				sb.WriteString(fmt.Sprintf("      - privilege: %s\n", perm.Privilege))
				sb.WriteString(fmt.Sprintf("        object_type: %s\n", perm.ObjectType))
				sb.WriteString(fmt.Sprintf("        object_name: %s\n", perm.ObjectName))
				if perm.Schema != "" {
					sb.WriteString(fmt.Sprintf("        schema: %s\n", perm.Schema))
				}
			}
		}
	}

	return sb.String()
}
