image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-test-lab-service
  tag: replace-with-ci-tag
service:
  port: 7202
env:
  ENV: prod
  SERVICE_PORT: '7202'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  PLAYWRIGHT_WORKERS: ''
  GRID_URL: ''
  PREVIEW_TTL_MIN: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: test-lab-service-secrets
  remotePath: secret/data/lma/test-lab-service/prod
  keys: []
