image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-webhook-relay-service
  tag: replace-with-ci-tag
service:
  port: 7903
env:
  ENV: staging
  SERVICE_PORT: '7903'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
  DLQ_STREAM: ''
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: webhook-relay-service-secrets
  remotePath: secret/data/lma/webhook-relay-service/staging
  keys:
  - WEBHOOK_SIGNING_SECRET
