image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-snapshot-orchestrator-service
  tag: replace-with-ci-tag
service:
  port: 7054
env:
  ENV: prod
  SERVICE_PORT: '7054'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  SNAPSHOT_TTL_HOURS: ''
  PIPELINE_TOPIC: ''
  S3_SNAPSHOT_PREFIX: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: snapshot-orchestrator-service-secrets
  remotePath: secret/data/lma/snapshot-orchestrator-service/prod
  keys: []
