apiVersion: v1
kind: Service
metadata:
  name: db-guardian-service
spec:
  type: ClusterIP
  selector: { app: db-guardian-service }
  ports:
    - name: http
      port: 7105
      targetPort: 7105
    {{- if .Values.grpc.enabled }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
    {{- end }}
