apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: observability-service-deny-all
spec:
  podSelector:
    matchLabels:
      app: observability-service
  policyTypes: ["Ingress","Egress"]
  ingress: [{}]
  egress: [{}]
