apiVersion: v1
kind: Service
metadata:
  name: observability-service
spec:
  type: ClusterIP
  selector: { app: observability-service }
  ports:
    - name: http
      port: 7301
      targetPort: 7301
