import { describe, expect, test } from 'vitest';
import { loadConfig } from './config';

describe('config reliability', () => {
  test('applies sensible defaults', () => {
    const saved = { ...process.env };
    delete process.env.CHANNEL_TIMEOUT_MS;
    delete process.env.CHANNEL_RETRY_MAX;
    delete process.env.CHANNEL_RETRY_BASE_MS;
    delete process.env.CHANNEL_RETRY_JITTER_PCT;
    delete process.env.CHANNEL_BREAKER_FAILURE_THRESHOLD;
    delete process.env.CHANNEL_BREAKER_WINDOW_SIZE;
    delete process.env.CHANNEL_BREAKER_HALF_OPEN_MS;
    process.env.ENV = 'dev';
    process.env.SERVICE_NAME = 'notification-service';
    process.env.SERVICE_PORT = '7902';
    process.env.OTEL_EXPORTER_OTLP_ENDPOINT = 'http://localhost:4318';
    process.env.SMTP_HOST = 'localhost';
    process.env.SMTP_PORT = '25';
    process.env.SMTP_USER = 'u';
    process.env.SMTP_PASSWORD = 'p';
    process.env.SMTP_FROM = 'noreply@example.com';
    process.env.VAULT_ADDR = 'http://vault:8200';
    process.env.VAULT_ROLE_ID = 'role';
    process.env.VAULT_SECRET_ID = 'secret';
    // Required PG vars for loadConfig
    process.env.PG_HOST = 'localhost';
    process.env.PG_PORT = '5432';
    process.env.PG_DATABASE = 'lma';
    process.env.PG_USER = 'postgres';
    process.env.PG_PASSWORD = 'postgres';
    const cfg = loadConfig();
    expect(cfg.reliability.timeoutMs).toBe(5000);
    expect(cfg.reliability.retry.max).toBe(3);
    expect(cfg.reliability.retry.baseMs).toBe(250);
    expect(cfg.reliability.retry.jitterPct).toBeCloseTo(0.2);
    expect(cfg.reliability.breaker.failureThreshold).toBe(3);
    expect(cfg.reliability.breaker.windowSize).toBe(10);
    expect(cfg.reliability.breaker.halfOpenAfterMs).toBe(15000);
    process.env = saved as any;
  });

  test('parses overrides', () => {
    const saved = { ...process.env };
    process.env.CHANNEL_TIMEOUT_MS = '1234';
    process.env.CHANNEL_RETRY_MAX = '5';
    process.env.CHANNEL_RETRY_BASE_MS = '111';
    process.env.CHANNEL_RETRY_JITTER_PCT = '0.5';
    process.env.CHANNEL_BREAKER_FAILURE_THRESHOLD = '7';
    process.env.CHANNEL_BREAKER_WINDOW_SIZE = '13';
    process.env.CHANNEL_BREAKER_HALF_OPEN_MS = '30000';
    process.env.ENV = 'dev';
    process.env.SERVICE_NAME = 'notification-service';
    process.env.SERVICE_PORT = '7902';
    process.env.OTEL_EXPORTER_OTLP_ENDPOINT = 'http://localhost:4318';
    process.env.SMTP_HOST = 'localhost';
    process.env.SMTP_PORT = '25';
    process.env.SMTP_USER = 'u';
    process.env.SMTP_PASSWORD = 'p';
    process.env.SMTP_FROM = 'noreply@example.com';
    process.env.VAULT_ADDR = 'http://vault:8200';
    process.env.VAULT_ROLE_ID = 'role';
    process.env.VAULT_SECRET_ID = 'secret';
    process.env.PG_HOST = 'localhost';
    process.env.PG_PORT = '5432';
    process.env.PG_DATABASE = 'lma';
    process.env.PG_USER = 'postgres';
    process.env.PG_PASSWORD = 'postgres';
    const cfg = loadConfig();
    expect(cfg.reliability.timeoutMs).toBe(1234);
    expect(cfg.reliability.retry.max).toBe(5);
    expect(cfg.reliability.retry.baseMs).toBe(111);
    expect(cfg.reliability.retry.jitterPct).toBeCloseTo(0.5);
    expect(cfg.reliability.breaker.failureThreshold).toBe(7);
    expect(cfg.reliability.breaker.windowSize).toBe(13);
    expect(cfg.reliability.breaker.halfOpenAfterMs).toBe(30000);
    process.env = saved as any;
  });
});
