apiVersion: v1
kind: Service
metadata:
  name: authz-matrix-service
spec:
  type: ClusterIP
  selector: { app: authz-matrix-service }
  ports:
    - name: http
      port: 7203
      targetPort: 7203
