apiVersion: v1
kind: Service
metadata:
  name: dep-governance-service
spec:
  type: ClusterIP
  selector: { app: dep-governance-service }
  ports:
    - name: http
      port: 7106
      targetPort: 7106
