image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-positioning-engine-service
  tag: replace-with-ci-tag
service:
  port: 7501
env:
  ENV: prod
  SERVICE_PORT: '7501'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  VERTICAL_CORPORA_S3: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: positioning-engine-service-secrets
  remotePath: secret/data/lma/positioning-engine-service/prod
  keys:
  - EMBEDDING_API_KEY
