apiVersion: v1
kind: Service
metadata:
  name: webhook-relay-service
spec:
  type: ClusterIP
  selector: { app: webhook-relay-service }
  ports:
    - name: http
      port: 7903
      targetPort: 7903
