image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-motivation-engine-service
  tag: replace-with-ci-tag
service:
  port: 7601
env:
  ENV: staging
  SERVICE_PORT: '7601'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
  NUDGE_HEURISTICS_JSON: ''
  WS_CLUSTER_ID: ''
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: motivation-engine-service-secrets
  remotePath: secret/data/lma/motivation-engine-service/staging
  keys: []
