image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-rate-limit-service
  tag: replace-with-ci-tag
service:
  port: 7204
env:
  ENV: prod
  SERVICE_PORT: '7204'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  REDIS_URL: ''
  DEFAULT_RPM: ''
  BURST_MULTIPLIER: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: rate-limit-service-secrets
  remotePath: secret/data/lma/rate-limit-service/prod
  keys: []
