// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: dbguardian/v1/dbguardian.proto

package dbguardianv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DbGuardianService_RegisterConnection_FullMethodName = "/dbguardian.v1.DbGuardianService/RegisterConnection"
	DbGuardianService_ListConnections_FullMethodName    = "/dbguardian.v1.DbGuardianService/ListConnections"
	DbGuardianService_ValidateMigration_FullMethodName  = "/dbguardian.v1.DbGuardianService/ValidateMigration"
	DbGuardianService_RunAnalysis_FullMethodName        = "/dbguardian.v1.DbGuardianService/RunAnalysis"
	DbGuardianService_GetRecommendations_FullMethodName = "/dbguardian.v1.DbGuardianService/GetRecommendations"
	DbGuardianService_GetPolicy_FullMethodName          = "/dbguardian.v1.DbGuardianService/GetPolicy"
	DbGuardianService_UpdatePolicy_FullMethodName       = "/dbguardian.v1.DbGuardianService/UpdatePolicy"
	DbGuardianService_CheckDrift_FullMethodName         = "/dbguardian.v1.DbGuardianService/CheckDrift"
)

// DbGuardianServiceClient is the client API for DbGuardianService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbGuardianServiceClient interface {
	RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*RegisterConnectionResponse, error)
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	ValidateMigration(ctx context.Context, in *ValidateMigrationRequest, opts ...grpc.CallOption) (*ValidateMigrationResponse, error)
	RunAnalysis(ctx context.Context, in *RunAnalysisRequest, opts ...grpc.CallOption) (*RunAnalysisResponse, error)
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error)
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error)
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error)
	CheckDrift(ctx context.Context, in *CheckDriftRequest, opts ...grpc.CallOption) (*CheckDriftResponse, error)
}

type dbGuardianServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbGuardianServiceClient(cc grpc.ClientConnInterface) DbGuardianServiceClient {
	return &dbGuardianServiceClient{cc}
}

func (c *dbGuardianServiceClient) RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*RegisterConnectionResponse, error) {
	out := new(RegisterConnectionResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_RegisterConnection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_ListConnections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) ValidateMigration(ctx context.Context, in *ValidateMigrationRequest, opts ...grpc.CallOption) (*ValidateMigrationResponse, error) {
	out := new(ValidateMigrationResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_ValidateMigration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) RunAnalysis(ctx context.Context, in *RunAnalysisRequest, opts ...grpc.CallOption) (*RunAnalysisResponse, error) {
	out := new(RunAnalysisResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_RunAnalysis_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error) {
	out := new(GetRecommendationsResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_GetRecommendations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error) {
	out := new(GetPolicyResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_GetPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error) {
	out := new(UpdatePolicyResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_UpdatePolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbGuardianServiceClient) CheckDrift(ctx context.Context, in *CheckDriftRequest, opts ...grpc.CallOption) (*CheckDriftResponse, error) {
	out := new(CheckDriftResponse)
	err := c.cc.Invoke(ctx, DbGuardianService_CheckDrift_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbGuardianServiceServer is the server API for DbGuardianService service.
// All implementations must embed UnimplementedDbGuardianServiceServer
// for forward compatibility
type DbGuardianServiceServer interface {
	RegisterConnection(context.Context, *RegisterConnectionRequest) (*RegisterConnectionResponse, error)
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	ValidateMigration(context.Context, *ValidateMigrationRequest) (*ValidateMigrationResponse, error)
	RunAnalysis(context.Context, *RunAnalysisRequest) (*RunAnalysisResponse, error)
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error)
	CheckDrift(context.Context, *CheckDriftRequest) (*CheckDriftResponse, error)
	mustEmbedUnimplementedDbGuardianServiceServer()
}

// UnimplementedDbGuardianServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDbGuardianServiceServer struct {
}

func (UnimplementedDbGuardianServiceServer) RegisterConnection(context.Context, *RegisterConnectionRequest) (*RegisterConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConnection not implemented")
}
func (UnimplementedDbGuardianServiceServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedDbGuardianServiceServer) ValidateMigration(context.Context, *ValidateMigrationRequest) (*ValidateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateMigration not implemented")
}
func (UnimplementedDbGuardianServiceServer) RunAnalysis(context.Context, *RunAnalysisRequest) (*RunAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAnalysis not implemented")
}
func (UnimplementedDbGuardianServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedDbGuardianServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedDbGuardianServiceServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedDbGuardianServiceServer) CheckDrift(context.Context, *CheckDriftRequest) (*CheckDriftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDrift not implemented")
}
func (UnimplementedDbGuardianServiceServer) mustEmbedUnimplementedDbGuardianServiceServer() {}

// UnsafeDbGuardianServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbGuardianServiceServer will
// result in compilation errors.
type UnsafeDbGuardianServiceServer interface {
	mustEmbedUnimplementedDbGuardianServiceServer()
}

func RegisterDbGuardianServiceServer(s grpc.ServiceRegistrar, srv DbGuardianServiceServer) {
	s.RegisterService(&DbGuardianService_ServiceDesc, srv)
}

func _DbGuardianService_RegisterConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).RegisterConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_RegisterConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).RegisterConnection(ctx, req.(*RegisterConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_ValidateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).ValidateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_ValidateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).ValidateMigration(ctx, req.(*ValidateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_RunAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).RunAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_RunAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).RunAnalysis(ctx, req.(*RunAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbGuardianService_CheckDrift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDriftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbGuardianServiceServer).CheckDrift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbGuardianService_CheckDrift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbGuardianServiceServer).CheckDrift(ctx, req.(*CheckDriftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbGuardianService_ServiceDesc is the grpc.ServiceDesc for DbGuardianService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbGuardianService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbguardian.v1.DbGuardianService",
	HandlerType: (*DbGuardianServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterConnection",
			Handler:    _DbGuardianService_RegisterConnection_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _DbGuardianService_ListConnections_Handler,
		},
		{
			MethodName: "ValidateMigration",
			Handler:    _DbGuardianService_ValidateMigration_Handler,
		},
		{
			MethodName: "RunAnalysis",
			Handler:    _DbGuardianService_RunAnalysis_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _DbGuardianService_GetRecommendations_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _DbGuardianService_GetPolicy_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _DbGuardianService_UpdatePolicy_Handler,
		},
		{
			MethodName: "CheckDrift",
			Handler:    _DbGuardianService_CheckDrift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbguardian/v1/dbguardian.proto",
}
