image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-launch-engine-service
  tag: replace-with-ci-tag
service:
  port: 7502
env:
  ENV: staging
  SERVICE_PORT: '7502'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: launch-engine-service-secrets
  remotePath: secret/data/lma/launch-engine-service/staging
  keys:
  - TWITTER_API_KEY
  - REDDIT_CLIENT_ID
  - PH_TOKEN
