apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: notification-service }
  template:
    metadata:
      labels: { app: notification-service }
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          {{- range $name, $val := .Values.env }}
            - name: {{ $name }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecrets.targetName }}
          {{- end }}
          ports:
            - containerPort: 7902
          readinessProbe:
            httpGet: { path: /healthz, port: 7902 }
            initialDelaySeconds: 2
          livenessProbe:
            httpGet: { path: /healthz, port: 7902 }
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
