{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.storeRefName }}
  target:
    name: {{ .Values.externalSecrets.targetName }}
    creationPolicy: Owner
  data:
  {{- range $k := .Values.externalSecrets.keys }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remotePath }}
        property: {{ $k }}
  {{- end }}
{{- end }}
