image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-finops-service
  tag: replace-with-ci-tag
service:
  port: 7401
env:
  ENV: staging
  SERVICE_PORT: '7401'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-staging.svc.cluster.local:4317
  CLOUD_COST_EXPORT_S3: ''
  FORECAST_HORIZON_DAYS: ''
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: '1'
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
externalSecrets:
  enabled: true
  storeRefName: vault-staging
  targetName: finops-service-secrets
  remotePath: secret/data/lma/finops-service/staging
  keys:
  - STRIPE_API_KEY
