image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-dep-governance-service
  tag: replace-with-ci-tag
service:
  port: 7106
env:
  ENV: prod
  SERVICE_PORT: '7106'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-prod.svc.cluster.local:4317
  SYFT_OPTS: ''
  GRYPE_DB_DIR: ''
  LICENSE_ALLOWLIST: ''
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: '2'
    memory: 2Gi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
externalSecrets:
  enabled: true
  storeRefName: vault-prod
  targetName: dep-governance-service-secrets
  remotePath: secret/data/lma/dep-governance-service/prod
  keys: []
