image:
  repository: ghcr.io/{{ORG}}/{{REPO}}-dep-governance-service
  tag: dev
service:
  port: 7106
env:
  ENV: dev
  SERVICE_PORT: '7106'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.lma-dev.svc.cluster.local:4317
  SYFT_OPTS: ''
  GRYPE_DB_DIR: ''
  LICENSE_ALLOWLIST: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
hpa:
  enabled: false
externalSecrets:
  enabled: true
  storeRefName: vault-dev
  targetName: dep-governance-service-secrets
  remotePath: secret/data/lma/dep-governance-service/dev
  keys: []
