name: ci-fe-mode-c-zip-uploader
on:
  push: { branches: [ main ], paths: [ 'frontends/mode-c-zip-uploader/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_frontend-ci.yml
    with:
      context: frontends/mode-c-zip-uploader
      dockerfile: frontends/mode-c-zip-uploader/Dockerfile
      image_suffix: fe-mode-c-zip-uploader
