name: ci-motivation-engine-service
on:
  push: { branches: [ main ], paths: [ 'services/motivation-engine-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: node
      context: services/motivation-engine-service
      dockerfile: services/motivation-engine-service/Dockerfile
      image_suffix: motivation-engine-service
