name: ci-notification-service
on:
  push: { branches: [ main ], paths: [ 'services/notification-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: node
      context: services/notification-service
      dockerfile: services/notification-service/Dockerfile
      image_suffix: notification-service
