name: ci-observability-service
on:
  push: { branches: [ main ], paths: [ 'services/observability-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: go
      context: services/observability-service
      dockerfile: services/observability-service/Dockerfile
      image_suffix: observability-service
