name: ci-projects-service
on:
  push: { branches: [ main ], paths: [ 'services/projects-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: node
      context: services/projects-service
      dockerfile: services/projects-service/Dockerfile
      image_suffix: projects-service
