name: ci-rate-limit-service
on:
  push: { branches: [ main ], paths: [ 'services/rate-limit-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: go
      context: services/rate-limit-service
      dockerfile: services/rate-limit-service/Dockerfile
      image_suffix: rate-limit-service
