name: ci-scm-app-service
on:
  push: { branches: [ main ], paths: [ 'services/scm-app-service/**' ] }
jobs:
  call:
    uses: ./.github/workflows/_service-ci.yml
    with:
      lang: go
      context: services/scm-app-service
      dockerfile: services/scm-app-service/Dockerfile
      image_suffix: scm-app-service
